### ISSUE TITLE
Zimit Videos are not playable on kiwix-desktop Windows

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-desktop#1276]
With cutting edge dev version of Kiwix Desktop on Windows
(download ZIM at https://dev.library.kiwix.org/#lang=&q=quartier)

See
![Image](https://github.com/user-attachments/assets/abd9a1e4-a12f-4263-bedf-0646e7d97e2e)

But it works online:
https://dev.library.kiwix.org/viewer#mes-quartiers-chinois_fr_all_2024-12/mesquartierschinois.wordpress.com/

**Comment by kelson42** [comment]
@benoit74 MIght that be that we have some kind of problem with the user-agent or the resolution?

**Comment by benoit74** [comment]
Testing with https://dev.library.kiwix.org/#lang=eng&q=zimit+test+website, it is now clear that the problem is not specific to Youtube but all (even very straightforward) inline JS.

If you go to "Javascript" page on this test website, we see that all inline JS are failing (while working online in kiwix-serve at https://dev.library.kiwix.org/viewer#website.test.openzim.org_en_all_2024-12/website.test.openzim.org/javascript.html and in all other browers if I'm not mistaken).

@veloman-yunkan do you have any clue where to loom at?

Problem is already present in 2.3.1, so for me this is not an issue which should stop release of 2.4.0

**Comment by kelson42** [comment]
@benoit74 Thank you very much for the analysis! @veloman-yunkan if there is something unclear how these ZIM are working, please request a meeting to @benoit74 so you can clarify things.

**Comment by benoit74** [comment]
Yes, do not hesitate, zimit test website is really "plain simple", so do not hesitate if you need a small tour, it will probably be quick to explain.

**Comment by veloman-yunkan** [comment]
In the Linux build of `kiwix-dekstop` the tests 01*, 08* and 09* for inline Javascript fail too:  

```
Various Javascript
On every lines below, you should see written "This is working OK"

01a. Simple inline Javascript with content on "normal" FQDN: This is not working

01b. Simple inline Javascript with content on "special chars" FQDN: This is not working

01c. Simple inline Javascript with content on "normal" FQDN and accentuated path: This is not working

01d. Simple inline Javascript with content on "special chars" FQDN and accentuated path: This is not working

01e. Simple inline Javascript with content on "normal" FQDN and utf-8 char in path: This is not working

01f. Simple inline Javascript with content on "special chars" FQDN and utf-8 char in path: This is not working

01g. Simple inline Javascript with content on "normal" FQDN and improperly escaped accentued char in path: This is not working

01h. Simple inline Javascript with content on "special chars" FQDN andimproperly escaped accentued char in path: This is not working

01i. Simple inline Javascript with content on improperly escaped "special chars" FQDN: This is not working

01j. Simple inline Javascript with content accessed with query parameter: This is not working

01k. Simple inline Javascript with content accessed with query parameter and query value containing an equal sign : This is not working

01l. Simple inline Javascript with content accessed with query parameter and query value containing a percent sign: This is not working

01m. Simple inline Javascript with content URL containing an interogation point sign: This is not working

01n. Simple inline Javascript with content URL containing an interogation point sign and a query parameter: This is not working

01o. Simple inline Javascript with content on "normal" FQDN and improperly escaped utf-8 char in path: This is not working

01p. Simple inline Javascript with content on "special chars" FQDN and improperly escaped utf-8 char in path: This is not working

01q. Simple inline Javascript with content on relative path and improperly escaped utf-8 char in path: This is not working

01r. Simple inline Javascript with content on relative path and exclamation mark in path: This is not working

02a. Simple classic Javascript with simple src: This is working OK

02b. Simple classic Javascript with src and exclamation mark in path: This is working OK

03. Simple classic Javascript with src and type: This is working OK

04. Simple classic Javascript onload: This is working OK

05. Simple classic Javascript preload as script: This is working OK

06a. Simple module Javascript with src and type - nominal case: This is working OK

06b. Simple module Javascript with src and type - unused vars: This is working OK

06c. Simple module Javascript with src and type - absolute path: This is working OK

06d. Simple module Javascript with src and type - parent path: This is working OK

06e. Simple module Javascript with src and type - accentuated path: This is working OK

06f. Simple module Javascript with src and type - querystring: This is working OK

06g. Simple module Javascript with src and type - querystring with equal sign in value: This is working OK

06h. Simple module Javascript with src and type - querystring with percent sign in value: This is working OK

06i. Simple module Javascript with src and type - interogation sign in path: This is working OK

06j. Simple module Javascript with src and type - interogation sign in path and querystring: This is working OK

07. Simple module Javascript with modulepreload: This is working OK

08a. Simple module Javascript with importmap required: This is not working

08b. Simple module Javascript with importmap required: This is not working

08c. Simple module Javascript with importmap required: This is not working

09a. Simple module Javascript with importmap required but nasty URL used in JS: This is not working

09b. Simple module Javascript with importmap required but nasty URL used in JS: This is not working

09c. Simple module Javascript with importmap required but nasty URL used in JS: This is not working

09d. Simple module Javascript with importmap required but nasty URL used in JS: This is not working

10. Rewritting image src dynamically based on already statically rewritten link: This is working OK```

**Comment by veloman-yunkan** [comment]
By looking at the HTML source of the [inline Javascript test page](https://dev.library.kiwix.org/content/website.test.openzim.org_en_all_2024-12/website.test.openzim.org/javascript.html) (the snapshot is saved [here](https://github.com/user-attachments/files/18080213/https___dev.library.kiwix.org_content_website.test.openzim.org_en_all_2024-12_website.test.openzim.org_javascript.zip))  it's not surprising that the 01[a-r] tests fail - they all fetch data from an external URL (located at https://website.test.openzim.org/ or https://xn--wbsite-bva.test.openzim.org/).

**Comment by veloman-yunkan** [comment]
> In the Linux build of `kiwix-dekstop` the tests 01*, 08* and 09* for inline Javascript fail too:

The set of failing tests is identical across Linux and Windows.

Whereas the problem with video playback is only under Windows.

**Comment by veloman-yunkan** [comment]
It looks like in the Qt build used in our CI/CD under Windows proprietary audio and video codecs have **not** been enabled.

**Comment by benoit74** [comment]
Thank you! Let's focus back this issue on video problem on Windows then, looks like these are distinct issues.

**Comment by kelson42** [comment]
> It looks like in the Qt build used in our CI/CD under Windows proprietary audio and video codecs have **not** been enabled.
> 
> https://doc.qt.io/qt-5/qtwebengine-features.html#audio-and-video-codecs
> 
> > Qt WebEngine supports the MPEG-4 Part 14 (MP4) file format only if the required proprietary audio and video codecs, such as H.264 and MPEG layer-3 (MP3), have been enabled.

We should not have to activate the support of these propriatary codecs because we use webm. In addition we should not because this would imply probably paying license fee for our distributed software.

**Comment by benoit74** [comment]
I've opened https://github.com/kiwix/kiwix-desktop/issues/1281 for the inline JS part

**Comment by benoit74** [comment]
> We should not have to activate the support of these propriatary codecs because we use webm. In addition we should not because this would imply probably paying license fee for our distributed software.

We do not use webm on zimit ZIMs, we use whatever the youtube player decided to use. And it might be mp4. And indeed, this video is mp4.

**Comment by benoit74** [comment]
I've asked the question to webrecorder team to have a bit more details about where mp4 comes from: https://github.com/webrecorder/browsertrix-crawler/issues/732

**Comment by kelson42** [comment]
> I've asked the question to webrecorder team to have a bit more details about where mp4 comes from: [webrecorder/browsertrix-crawler#732](https://github.com/webrecorder/browsertrix-crawler/issues/732)

@benoit74 Thank you, I think we have two issues:
* We should better scrape using webm if possible, this is https://github.com/webrecorder/browsertrix-crawler/issues/732
* What about if we still have a mp4/h264 stuff? I have reopen https://github.com/kiwix/kiwix-desktop/issues/1029

**Comment by benoit74** [comment]
Now that I know how to debug kiwix-desktop ZIM, I've revisited this issue and I have a highly probable explanation (not related to webm/mp4/...).

The console log when opening this page has a bunch of `Uncaught TypeError: encodeURIComponent(...).replaceAll is not a function` errors:

<img width="517" height="111" alt="Image" src="https://github.com/user-attachments/assets/efb2cbe5-37b1-4bd4-a41a-261059ab37c8" />

Looking at the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll), it becomes obvious this is "pretty recent". 

Looking at https://wiki.qt.io/QtWebEngine/ChromiumVersions, we can say that we need Qt 5.15.3 for this to work.

And guess what? kiwix-desktop 2.4.1 was build on 5.15.2 ... that was close to work 🤣 

I tried to use nightly (2025-07-18) and this solves these errors about `replaceAll` ... but still does not load properly the Youtube video.

Instead of this "big" quartierchinois, I switched to https://dev.library.kiwix.org/content/website.test.openzim.org_en_all_2025-06/website.test.openzim.org/youtube.html for investigation, since this does not work as well on kiwix-desktop and is much simpler.

Here looking at the console logs + network event, I don't have much understanding.

It looks like we have very similar errors between opening link above in my Chrome (on MacOS) and opening same in kiwix-desktop. But then at some point it looks like Youtube player JS decides QT WebEngine Chromium is not capable to read the video and stops.

| Kiwix desktop on Windows | Chrome on MacOS |
|--|--|
| <img width="1124" height="587" alt="Image" src="https://github.com/user-attachments/assets/a628be87-c5d4-4901-826b-99da0c388399" /> | <img width="1271" height="357" alt="Image" src="https://github.com/user-attachments/assets/7cb3db11-ae46-40e1-8824-b84a1de10e42" /> |
| <img width="931" height="381" alt="Image" src="https://github.com/user-attachments/assets/6f0a7193-3fb7-4f84-99be-030f87b59e31" /> | <img width="1256" height="484" alt="Image" src="https://github.com/user-attachments/assets/389f3e39-d30d-4987-bc71-20ec740aa5db" /> |

Note also that opening this link in Edge on same Windows machine works fine, so it is not like we have a codec issue on this machine.

I don't know what's next.

**Comment by kelson42** [comment]
We have deprecated Qt5, see #1300. We should retest.

**Comment by benoit74** [comment]
Note that youtube videos are broken again in Zimit ATM. Ensure you use a ZIM which works well on kiwix-serve before testing on kiwix-desktop.
