### ISSUE TITLE
kiwix-desktop-2.3.1 does not build with libkiwix-12.1.1

### ISSUE THREAD

**Issue by hashworks** [kiwix/kiwix-desktop#1006]
Version 2.3.1 fails to build with latest libkiwix 12.1.1.

```
src/contentmanager.cpp: In member function ‘QStringList ContentManager::updateDownloadInfos(QString, const QStringList&)’:
src/contentmanager.cpp:178:57: error: no match for ‘operator=’ (operand types are ‘std::shared_ptr<kiwix::Download>’ and ‘kiwix::Download*’)
  178 |         d = mp_downloader->getDownload(b.getDownloadId());
```

Full log:
```
src/contentmanager.cpp:50:85: warning: ‘const std::string& kiwix::Book::getLanguage() const’ is deprecated [-Wdeprecated-declarations]
   50 | #define ADD_V(KEY, METH) {if(key==KEY) values.append(QString::fromStdString((b->METH())));}
      |                                                                              ~~~~~~~^~
src/contentmanager.cpp:77:9: note: in expansion of macro ‘ADD_V’
   77 |         ADD_V("language", getLanguage);
      |         ^~~~~
In file included from src/library.h:4,
                 from src/contentmanager.h:6,
                 from src/contentmanager.cpp:1:
/usr/include/kiwix/book.h:82:33: note: declared here
   82 |   DEPRECATED const std::string& getLanguage() const { return m_language; }
      |                                 ^~~~~~~~~~~
src/contentmanager.cpp: In member function ‘QStringList ContentManager::updateDownloadInfos(QString, const QStringList&)’:
src/contentmanager.cpp:178:57: error: no match for ‘operator=’ (operand types are ‘std::shared_ptr<kiwix::Download>’ and ‘kiwix::Download*’)
  178 |         d = mp_downloader->getDownload(b.getDownloadId());
      |                                                         ^
In file included from /usr/include/c++/13.2.1/memory:80,
                 from /usr/include/kiwix/book.h:25:
/usr/include/c++/13.2.1/bits/shared_ptr.h:418:9: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<const std::shared_ptr<_Yp>&> std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Yp>&) [with _Tp = kiwix::Download]’
  418 |         operator=(const shared_ptr<_Yp>& __r) noexcept
      |         ^~~~~~~~
/usr/include/c++/13.2.1/bits/shared_ptr.h:418:9: note:   template argument deduction/substitution failed:
src/contentmanager.cpp:178:57: note:   mismatched types ‘const std::shared_ptr<_Tp>’ and ‘kiwix::Download*’
  178 |         d = mp_downloader->getDownload(b.getDownloadId());
      |                                                         ^
/usr/include/c++/13.2.1/bits/shared_ptr.h:429:9: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<std::auto_ptr<_Up> > std::shared_ptr<_Tp>::operator=(std::auto_ptr<_Up>&&) [with _Tp = kiwix::Download]’
  429 |         operator=(auto_ptr<_Yp>&& __r)
      |         ^~~~~~~~
/usr/include/c++/13.2.1/bits/shared_ptr.h:429:9: note:   template argument deduction/substitution failed:
src/contentmanager.cpp:178:57: note:   mismatched types ‘std::auto_ptr<_Up>’ and ‘kiwix::Download*’
  178 |         d = mp_downloader->getDownload(b.getDownloadId());
      |                                                         ^
/usr/include/c++/13.2.1/bits/shared_ptr.h:446:9: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<std::shared_ptr<_Yp> > std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Yp>&&) [with _Tp = kiwix::Download]’
  446 |         operator=(shared_ptr<_Yp>&& __r) noexcept
      |         ^~~~~~~~
/usr/include/c++/13.2.1/bits/shared_ptr.h:446:9: note:   template argument deduction/substitution failed:
src/contentmanager.cpp:178:57: note:   mismatched types ‘std::shared_ptr<_Tp>’ and ‘kiwix::Download*’
  178 |         d = mp_downloader->getDownload(b.getDownloadId());
      |                                                         ^
/usr/include/c++/13.2.1/bits/shared_ptr.h:454:9: note: candidate: ‘template<class _Yp, class _Del> std::shared_ptr<_Tp>::_Assignable<std::unique_ptr<_Up, _Ep> > std::shared_ptr<_Tp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Del = _Yp; _Tp = kiwix::Download]’
  454 |         operator=(unique_ptr<_Yp, _Del>&& __r)
      |         ^~~~~~~~
/usr/include/c++/13.2.1/bits/shared_ptr.h:454:9: note:   template argument deduction/substitution failed:
src/contentmanager.cpp:178:57: note:   mismatched types ‘std::unique_ptr<_Tp, _Dp>’ and ‘kiwix::Download*’
  178 |         d = mp_downloader->getDownload(b.getDownloadId());
      |                                                         ^
/usr/include/c++/13.2.1/bits/shared_ptr.h:414:19: note: candidate: ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Tp>&) [with _Tp = kiwix::Download]’
  414 |       shared_ptr& operator=(const shared_ptr&) noexcept = default;
      |                   ^~~~~~~~
/usr/include/c++/13.2.1/bits/shared_ptr.h:414:29: note:   no known conversion for argument 1 from ‘kiwix::Download*’ to ‘const std::shared_ptr<kiwix::Download>&’
  414 |       shared_ptr& operator=(const shared_ptr&) noexcept = default;
      |                             ^~~~~~~~~~~~~~~~~
/usr/include/c++/13.2.1/bits/shared_ptr.h:438:7: note: candidate: ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Tp>&&) [with _Tp = kiwix::Download]’
  438 |       operator=(shared_ptr&& __r) noexcept
      |       ^~~~~~~~
/usr/include/c++/13.2.1/bits/shared_ptr.h:438:30: note:   no known conversion for argument 1 from ‘kiwix::Download*’ to ‘std::shared_ptr<kiwix::Download>&&’
  438 |       operator=(shared_ptr&& __r) noexcept
      |                 ~~~~~~~~~~~~~^~~
src/contentmanager.cpp: In member function ‘QString ContentManager::downloadBook(const QString&)’:
src/contentmanager.cpp:277:71: error: no match for ‘operator=’ (operand types are ‘std::shared_ptr<kiwix::Download>’ and ‘kiwix::Download*’)
  277 |         download = mp_downloader->startDownload(book.getUrl(), options);
      |                                                                       ^
/usr/include/c++/13.2.1/bits/shared_ptr.h:418:9: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<const std::shared_ptr<_Yp>&> std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Yp>&) [with _Tp = kiwix::Download]’
  418 |         operator=(const shared_ptr<_Yp>& __r) noexcept
      |         ^~~~~~~~
/usr/include/c++/13.2.1/bits/shared_ptr.h:418:9: note:   template argument deduction/substitution failed:
src/contentmanager.cpp:277:71: note:   mismatched types ‘const std::shared_ptr<_Tp>’ and ‘kiwix::Download*’
  277 |         download = mp_downloader->startDownload(book.getUrl(), options);
      |                                                                       ^
/usr/include/c++/13.2.1/bits/shared_ptr.h:429:9: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<std::auto_ptr<_Up> > std::shared_ptr<_Tp>::operator=(std::auto_ptr<_Up>&&) [with _Tp = kiwix::Download]’
  429 |         operator=(auto_ptr<_Yp>&& __r)
      |         ^~~~~~~~
/usr/include/c++/13.2.1/bits/shared_ptr.h:429:9: note:   template argument deduction/substitution failed:
src/contentmanager.cpp:277:71: note:   mismatched types ‘std::auto_ptr<_Up>’ and ‘kiwix::Download*’
  277 |         download = mp_downloader->startDownload(book.getUrl(), options);
      |                                                                       ^
/usr/include/c++/13.2.1/bits/shared_ptr.h:446:9: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<std::shared_ptr<_Yp> > std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Yp>&&) [with _Tp = kiwix::Download]’
  446 |         operator=(shared_ptr<_Yp>&& __r) noexcept
      |         ^~~~~~~~
/usr/include/c++/13.2.1/bits/shared_ptr.h:446:9: note:   template argument deduction/substitution failed:
src/contentmanager.cpp:277:71: note:   mismatched types ‘std::shared_ptr<_Tp>’ and ‘kiwix::Download*’
  277 |         download = mp_downloader->startDownload(book.getUrl(), options);
      |                                                                       ^
/usr/include/c++/13.2.1/bits/shared_ptr.h:454:9: note: candidate: ‘template<class _Yp, class _Del> std::shared_ptr<_Tp>::_Assignable<std::unique_ptr<_Up, _Ep> > std::shared_ptr<_Tp>::operator=(std::unique_ptr<_Up, _Ep>&&) [with _Del = _Yp; _Tp = kiwix::Download]’
  454 |         operator=(unique_ptr<_Yp, _Del>&& __r)
      |         ^~~~~~~~
/usr/include/c++/13.2.1/bits/shared_ptr.h:454:9: note:   template argument deduction/substitution failed:
src/contentmanager.cpp:277:71: note:   mismatched types ‘std::unique_ptr<_Tp, _Dp>’ and ‘kiwix::Download*’
  277 |         download = mp_downloader->startDownload(book.getUrl(), options);
      |                                                                       ^
/usr/include/c++/13.2.1/bits/shared_ptr.h:414:19: note: candidate: ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Tp>&) [with _Tp = kiwix::Download]’
  414 |       shared_ptr& operator=(const shared_ptr&) noexcept = default;
      |                   ^~~~~~~~
/usr/include/c++/13.2.1/bits/shared_ptr.h:414:29: note:   no known conversion for argument 1 from ‘kiwix::Download*’ to ‘const std::shared_ptr<kiwix::Download>&’
  414 |       shared_ptr& operator=(const shared_ptr&) noexcept = default;
      |                             ^~~~~~~~~~~~~~~~~
/usr/include/c++/13.2.1/bits/shared_ptr.h:438:7: note: candidate: ‘std::shared_ptr<_Tp>& std::shared_ptr<_Tp>::operator=(std::shared_ptr<_Tp>&&) [with _Tp = kiwix::Download]’
  438 |       operator=(shared_ptr&& __r) noexcept
      |       ^~~~~~~~
/usr/include/c++/13.2.1/bits/shared_ptr.h:438:30: note:   no known conversion for argument 1 from ‘kiwix::Download*’ to ‘std::shared_ptr<kiwix::Download>&&’
  438 |       operator=(shared_ptr&& __r) noexcept
      |                 ~~~~~~~~~~~~~^~~
/usr/bin/rcc -name kiwix resources/kiwix.qrc -o qrc_kiwix.cpp
/usr/bin/rcc -name translations resources/translations.qrc -o qrc_translations.cpp
/usr/bin/rcc -name contentmanager resources/contentmanager.qrc -o qrc_contentmanager.cpp
/usr/bin/rcc -name settingsmanager resources/settingsmanager.qrc -o qrc_settingsmanager.cpp
/usr/bin/rcc -name style resources/style.qrc -o qrc_style.cpp
g++ -pipe -std=c++11 -I/usr/include/ -I/usr/include/p11-kit-1 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/kiwix-desktop/src=/usr/src/debug/kiwix-desktop -flto=auto -flto -fno-fat-lto-objects -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp
g++ -c -pipe -std=c++11 -I/usr/include/ -I/usr/include/p11-kit-1 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/kiwix-desktop/src=/usr/src/debug/kiwix-desktop -flto=auto -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC -DVERSION=2.3.1 -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WEBENGINEWIDGETS_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB -I. -Isubprojects/QtSingleApplication/src -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o findinpagebar.o src/findinpagebar.cpp
g++ -c -pipe -std=c++11 -I/usr/include/ -I/usr/include/p11-kit-1 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -g -ffile-prefix-map=/build/kiwix-desktop/src=/usr/src/debug/kiwix-desktop -flto=auto -flto -fno-fat-lto-objects -Wall -Wextra -D_REENTRANT -fPIC -DVERSION=2.3.1 -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WEBENGINEWIDGETS_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB -I. -Isubprojects/QtSingleApplication/src -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o mainwindow.o src/mainwindow.cpp
make: *** [Makefile:1607: contentmanager.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by kelson42** [comment]
We wil release 2.4.0 based on libkiwix 13.0.0

**Comment by mgautierfr** [comment]
Are you sure you are using libkiwix `12.1.1` ?
Version `12.1.0` is indeed return a `shared_ptr<Download>` (https://github.com/kiwix/libkiwix/blob/12.1.0/include/downloader.h#L197)
But version `12.1.1` is returning a `Download*` (https://github.com/kiwix/libkiwix/blob/12.1.1/include/downloader.h#L197)

The purpose of 12.1.1 was to fix this API break wrongly introduced in `12.1.0`.

**Comment by hashworks** [comment]
Ah, my bad. I still included commit 1b322d8f01c787846546a6473f153cf1daa41e65 from https://github.com/kiwix/kiwix-desktop/issues/964#issuecomment-1646651036
